#!/usr/bin/zsh

case "$BLOCK_BUTTON" in
    1) notify-send "Downloading latest Zimpler VPN" && \
        arthur vpn-config update-networkmanager && \
        notify-send "Done. Latest Zimpler VPN installed" ;;
esac

CERT=false

CMD=$(~/.local/bin/certcheck ~/.cert/nm-openvpn/zimpler-staging-cert.pem)
if [ $? -eq 1 ]; then
    CERT="[ Zimpler CERT exp ]"
fi

if [ "$CERT" != "false" ]; then
    echo $CERT
else
    exit 0
fi

echo "" # short_text
echo "#fc2003" # color
echo "#000000" # background color

