#!/usr/bin/zsh
CERT=false

# Textalk certificate
TEXTALK=$(~/.local/bin/certcheck ~/Documents/vpn/abicart/cert.pem)
if [ $? -eq 1 ]; then
    CERT="Abicart VPN certificate expired!"
fi

if [ "$CERT" != "false" ]; then
    echo $CERT
else
    exit 0
fi

echo "" # short_text
echo "#fc2003" # color
echo "#000000" # background color

