#!/bin/bash
PWD=$(pwd)

install_deps() {
    sudo pacman -Sy --needed base-devel cmake unzip ninja tree-sitter curl
}

build_neovim() {
        cd ~/.build/neovim && git fetch && git checkout  v0.8.0 && git pull
    make distclean && make CMAKE_BUILD_TYPE=Release && sudo make install
}

[[ ! -d "${HOME}/.build" ]] && \
    mkdir ~/.build && \
    cd ~/.build && \
    git clone git@github.com:neovim/neovim.git

install_deps && build_neovim && cd $PWD
