#!/bin/bash

INSTALL_PACKAGES=(
    alacritty
    dmenu-manjaro
    firefox
    go
    i3-gaps
    i3blocks
    npm
    redshift
    ripgrep
    ttf-liberation
    xclip
    xorg-xbacklight
    xorg-xrandr
    xwallpaper
    zsh
)

echo "Installing packages: ${INSTALL_PACKAGES[@]}"
sudo pacman -Sy --needed ${INSTALL_PACKAGES[@]}
